name: Build images for Main branch
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
env:
  QUAY_ORG: opendatahub
  QUAY_ID: ${{ secrets.QUAY_ROBOT_USERNAME }}
  QUAY_TOKEN: ${{ secrets.QUAY_ROBOT_TOKEN }}
  SOURCE_BRANCH: main
jobs:
  build-main-images:
    continue-on-error: false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: ds-pipelines-argo-argoexec
            dockerfile: Dockerfile
          - image: ds-pipelines-argo-server
            dockerfile: Dockerfile
          - image: ds-pipelines-argo-workflowcontroller
            dockerfile: Dockerfile
    steps:
      - uses: actions/checkout@v3
      - name: Generate Tag
        shell: bash
        id: tags
        env:
          SOURCE_BRANCH: ${{ env.SOURCE_BRANCH }}
        run: |
          commit_sha=${{ github.event.after }}
          tag=${SOURCE_BRANCH}-${commit_sha:0:7}
          echo "tag=${tag}" >> $GITHUB_OUTPUT
      - name: Build Image
        uses: ./.github/actions/build
        env:
          IMG: quay.io/${{ env.QUAY_ORG }}/${{ matrix.image }}:${{ steps.tags.outputs.tag }}
          TARGET_IMAGE_TAG: ${{ steps.tags.outputs.tag }}
        with:
          OVERWRITE: true
          IMAGE_REPO: ${{ matrix.image }}
          DOCKERFILE: ${{ matrix.dockerfile }}
          GH_REPO: ${{ github.repository }}
      - name: Tag latest
        shell: bash
        env:
          IMG: quay.io/${{ env.QUAY_ORG }}/${{ matrix.image }}
          NEWEST_TAG: ${{ steps.tags.outputs.tag }}
          SOURCE_BRANCH: ${{ env.SOURCE_BRANCH }}
        run: |
          podman tag ${IMG}:${NEWEST_TAG} ${IMG}:latest
          podman push ${IMG}:latest
          podman tag ${IMG}:${NEWEST_TAG} ${IMG}:${SOURCE_BRANCH}
          podman push ${IMG}:${SOURCE_BRANCH}
